# Generated by Django 6.0.5 on 2026-06-02 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario_creacion', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario_modificacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=150, unique=True)),
                ('nombres', models.CharField(blank=True, max_length=100, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('documento', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario_creacion', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario_modificacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.DO_NOTHING, to='api_autenticacion.roles')),
            ],
            options={
                'db_table': 'usuarios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RecuperacionContrasena',
            fields=[
                ('id_recuperacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo_verificacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('usado', models.BooleanField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario_creacion', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario_modificacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='api_autenticacion.usuarios')),
            ],
            options={
                'db_table': 'recuperacion_contrasena',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ContrasenaHash',
            fields=[
                ('id_contrasena_hash', models.BigAutoField(primary_key=True, serialize=False)),
                ('contrasena_hash', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('usuario_creacion', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario_modificacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='api_autenticacion.usuarios')),
            ],
            options={
                'db_table': 'contrasena_hash',
                'managed': True,
            },
        ),
    ]
