# Generated by Django 6.0.5 on 2026-06-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodegas',
            fields=[
                ('id_bodegas', models.AutoField(primary_key=True, serialize=False)),
                ('id_empresa', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('capacidad_maxima', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField()),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bodegas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContrasenaHash',
            fields=[
                ('id_contrasena_hash', models.AutoField(primary_key=True, serialize=False)),
                ('contrasena_hash', models.CharField(max_length=255)),
                ('activo', models.BooleanField()),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contrasena_hash',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField()),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'empresas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id_moneda', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_moneda', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField()),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'moneda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecuperacionContrasena',
            fields=[
                ('id_recuperacion', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_verificacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('usado', models.BooleanField(blank=True, null=True)),
                ('activo', models.BooleanField()),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recuperacion_contrasena',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadesMedida',
            fields=[
                ('id_unidad_medida', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('sigla', models.CharField(blank=True, max_length=10, null=True)),
                ('activo', models.BooleanField()),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'unidades_medida',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='recuperacion_contrasena',
            name='id_usuario',
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='contrasena_hash',
        ),
        migrations.DeleteModel(
            name='recuperacion_contrasena',
        ),
    ]
