# Generated by Django 6.0.5 on 2026-06-02 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrasenahash',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='recuperacioncontrasena',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'managed': True},
        ),
    ]
