# Generated by Django 6.0.5 on 2026-06-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='backup',
            fields=[
                ('id_backup', models.AutoField(primary_key=True, serialize=False)),
                ('copia_seguridad', models.BooleanField()),
                ('frecuencia', models.CharField(max_length=50)),
                ('usuario_creacion', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario_modificacion', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('noti_stock_bajo', models.BooleanField()),
                ('noti_movimiento', models.BooleanField()),
                ('usuario_creacion', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario_modificacion', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='seguridad',
            fields=[
                ('id_seguridad', models.AutoField(primary_key=True, serialize=False)),
                ('tiempo_sesion', models.TimeField()),
                ('usuario_creacion', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario_modificacion', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='sistema',
            fields=[
                ('id_sistema', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('correo_empresa', models.EmailField(max_length=100)),
                ('usuario_creacion', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario_modificacion', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
