# Generated by Django 6.0.5 on 2026-06-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='usuario_creacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backup',
            name='usuario_modificacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='usuario_creacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='usuario_modificacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seguridad',
            name='usuario_creacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seguridad',
            name='usuario_modificacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sistema',
            name='usuario_creacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sistema',
            name='usuario_modificacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
