# Generated by Django 6.0.5 on 2026-06-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guias_entrada',
            name='usuario_creacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guias_entrada',
            name='usuario_modificacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='usuario_creacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='usuario_modificacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proveedor_productos',
            name='usuario_creacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proveedor_productos',
            name='usuario_modificacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guias_entrada',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
