# Generated by Django 6.0.5 on 2026-06-02 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_autenticacion', '0002_bodegas_contrasenahash_empresas_moneda_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bodegas',
        ),
        migrations.DeleteModel(
            name='Empresas',
        ),
        migrations.DeleteModel(
            name='Moneda',
        ),
        migrations.DeleteModel(
            name='UnidadesMedida',
        ),
        migrations.AlterModelTable(
            name='roles',
            table='roles',
        ),
        migrations.AlterModelTable(
            name='usuarios',
            table='usuarios',
        ),
    ]
