# Generated by Django 6.0.5 on 2026-06-02 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id_categoria_producto', models.AutoField(db_column='id_categoria_producto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario_creacion', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario_modificacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'categoria_producto',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(db_column='id_inventario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario_creacion', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario_modificacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventario',
            },
        ),
        migrations.CreateModel(
            name='TipoMovimiento',
            fields=[
                ('id_tipo_movimiento', models.AutoField(db_column='id_tipo_movimiento', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario_creacion', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario_modificacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tipos_movimiento',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(db_column='id_producto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_inicial', models.IntegerField(blank=True, default=0, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario_creacion', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario_modificacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_categoria_producto', models.ForeignKey(blank=True, db_column='id_categoria_producto', null=True, on_delete=django.db.models.deletion.CASCADE, to='api_inventario.categoriaproducto')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='InventarioProductos',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, default=0, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario_creacion', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario_modificacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_inventario', models.ForeignKey(blank=True, db_column='id_inventario', null=True, on_delete=django.db.models.deletion.CASCADE, to='api_inventario.inventario')),
                ('id_producto', models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.CASCADE, to='api_inventario.producto')),
            ],
            options={
                'db_table': 'inventario_productos',
            },
        ),
        migrations.CreateModel(
            name='Ajuste',
            fields=[
                ('id_ajuste', models.AutoField(db_column='id_ajuste', primary_key=True, serialize=False)),
                ('cantidad_esperada', models.IntegerField(blank=True, null=True)),
                ('cantidad_real', models.IntegerField(blank=True, null=True)),
                ('diferencia', models.IntegerField(blank=True, db_column='diferencia', editable=False, null=True)),
                ('motivo', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario_creacion', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario_modificacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_producto', models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.CASCADE, to='api_inventario.producto')),
            ],
            options={
                'db_table': 'ajustes',
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id_movimiento', models.AutoField(db_column='id_movimiento', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario_creacion', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario_modificacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_producto', models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.CASCADE, to='api_inventario.producto')),
                ('id_tipo_movimiento', models.ForeignKey(blank=True, db_column='id_tipo_movimiento', null=True, on_delete=django.db.models.deletion.CASCADE, to='api_inventario.tipomovimiento')),
            ],
            options={
                'db_table': 'movimientos',
            },
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id_transferencia', models.AutoField(db_column='id_transferencia', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario_creacion', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario_modificacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_producto', models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.CASCADE, to='api_inventario.producto')),
            ],
            options={
                'db_table': 'transferencia',
            },
        ),
    ]
