# Generated by Django 6.0.5 on 2026-05-28 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'categoria_producto',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_bodega', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventario',
            },
        ),
        migrations.CreateModel(
            name='TipoMovimiento',
            fields=[
                ('id_tipo_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tipos_movimiento',
            },
        ),
        migrations.CreateModel(
            name='InventarioProductos',
            fields=[
                ('id_inventario_producto', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('inventario', models.ForeignKey(db_column='inventario_id', on_delete=django.db.models.deletion.CASCADE, to='api_inventario.inventario')),
            ],
            options={
                'db_table': 'inventario_productos',
            },
        ),
        migrations.CreateModel(
            name='Ajuste',
            fields=[
                ('id_ajuste', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_ajustada', models.IntegerField()),
                ('motivo', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('inventario_producto', models.ForeignKey(db_column='inventario_producto_id', on_delete=django.db.models.deletion.CASCADE, to='api_inventario.inventarioproductos')),
            ],
            options={
                'db_table': 'ajustes',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(db_column='categoria_id', on_delete=django.db.models.deletion.CASCADE, to='api_inventario.categoriaproducto')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.AddField(
            model_name='inventarioproductos',
            name='producto',
            field=models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.CASCADE, to='api_inventario.producto'),
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('inventario', models.ForeignKey(db_column='inventario_id', on_delete=django.db.models.deletion.CASCADE, to='api_inventario.inventario')),
                ('producto', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.CASCADE, to='api_inventario.producto')),
                ('tipo_movimiento', models.ForeignKey(db_column='tipo_movimiento_id', on_delete=django.db.models.deletion.CASCADE, to='api_inventario.tipomovimiento')),
            ],
            options={
                'db_table': 'movimientos',
            },
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id_transferencia', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('estado', models.CharField(default='Pendiente', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('inventario_destino', models.ForeignKey(db_column='inventario_destino_id', on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_destino', to='api_inventario.inventario')),
                ('inventario_origen', models.ForeignKey(db_column='inventario_origen_id', on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_origen', to='api_inventario.inventario')),
                ('producto', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.CASCADE, to='api_inventario.producto')),
            ],
            options={
                'db_table': 'transferencia',
            },
        ),
    ]
